language: node_js
node_js:
  - "8"
cache:
  directories:
    "node_modules"
  before_script:
    - yarn build
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: yarn test -- --coverage && cat ./coverage/lcov.info | yarn coveralls && rm -rf ./coverage
